name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and Publish
      run: dotnet publish hello-world.csproj /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:SelfContained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:RuntimeIdentifier=win-x64 -o ./publish
      working-directory: ./hello-world
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloExe
        path: ./hello-world/publish/hello-world.exe
    
    - name: Get last artifact
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          $url = "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
          $response = Invoke-RestMethod -Uri $url -Headers @{ "Authorization" = "Bearer $env:GITHUB_TOKEN" }
          $lastArtifactUrl = $response.artifacts[0].archive_download_url
          echo "::set-output name=last-artifact-url::$lastArtifactUrl"
      id: last-artifact