name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and Publish
      run: dotnet publish -c Release -r win-x64 -o ./publish --self-contained true
      working-directory: ./hello-world
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourAppName
        path: ./hello-world/publish/hello-world.exe