name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and Publish
      run: dotnet publish hello-world.csproj /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:SelfContained=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:RuntimeIdentifier=win-x64 -o ./publish
      working-directory: ./hello-world
    
    - name: Download artifacts
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const artifacts = await github.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const latestArtifact = artifacts.data[0];
          console.log(`Latest artifact: ${latestArtifact.id}`);
          console.log(`Artifact URL: ${latestArtifact.archive_download_url}`);
          return {
            id: latestArtifact.id,
            url: latestArtifact.archive_download_url
          }

    - name: Update README
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const readme = await github.repos.getReadme({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const newContent = `Download the latest artifact [here](${{ steps.download.outputs.url }})`;
          await github.repos.createOrUpdateFileContents({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: readme.data.path,
            message: 'Update README',
            content: Buffer.from(newContent).toString('base64'),
            sha: readme.data.sha
          });